// Angular/AngularTodo/src/app/button/button.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-button',
  templateUrl: './button.component.html',
  styleUrls: ['./button.component.css'],
})
export class ButtonComponent implements OnInit {
  @Input('type') type: 'submit' | 'reset' | 'button' = 'button';
  @Input('color') color: 'primary' | 'secondary' | 'warn' | 'error' = 'primary';
  @Output('click') onClick: EventEmitter<Event> = new EventEmitter();

  constructor() {}

  ngOnInit(): void {}
}

<button [type]="type" [ngClass]="color" (click)="(onClick)">
  <ng-content></ng-content>
</button>

// React/react-todo/src/components/Button.jsx
import React from "react";
import styles from "./Button.module.css";

/**
 * Button component
 * @param {{
 *      children: any,
 *      type?: "submit" | "reset" | "button",
 *      color?: "primary" | "secondary" | "warn" | "error",
 *      onClick?: (event: React.MouseEvent<HTMLButtonElement>) => void,
 * }} props
 * @returns
 */
export default function Button(props) {
  const { children, type, color, onClick } = props;
  return (
    <button
      type={type ?? "button"}
      className={`${styles.btn} ${styles[color]}`}
      onClick={onClick}
    >
      {children}
    </button>
  );
}
